repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pypa/pip-audit
    rev: 'v2.5.6'
    hooks:
      -   id: pip-audit
          args: [--desc]
  # - repo: https://github.com/fpgmaas/deptry.git
  #   rev: '0.11.0'
  #   hooks:
  #     - id: deptry
  #       args: ["--skip-missing"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.269'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/grantjenks/blue.git
    rev: 'v0.9.1'
    hooks:
      - id: blue
        language_version: python3
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: 'v1.3.0'  # Use the sha / tag you want to point at
  #   hooks:
  #   - id: mypy

ci:
  # Leave pip-audit to only run locally and not in CI
  # pre-commit.ci does not allow network calls
  skip: [pip-audit]
